# Generated by ./configure script - Вт ноя 12 12:26:44 MSK 2019
# Modifications to this file are lost if ./configure is ran again.

CONF_VERSION = 1.0.5
CONF_CFLAGS = -Wall -O2 -g
CONF_ASN_CFLAGS = 
CONF_PREFIX = /usr/local
CONF_PRECOMPILED_ASN = yes
CONF_SUPL_DEBUG = -DSUPL_DEBUG
CONF_ASN1_SKELETONS = 
